// Package domain provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package domain

import (
	"time"
)

// CreateBundleRequest defines model for CreateBundleRequest.
type CreateBundleRequest struct {
	// Links Links in the bundle
	Links []Link `json:"links"`

	// Title Name of bundle (used in slug calculation)
	Title string `json:"title"`
}

// CreateBundleResponse defines model for CreateBundleResponse.
type CreateBundleResponse struct {
	CreatedAt time.Time `json:"createdAt"`

	// Slug URL-safe identifier for the bundle
	Slug string `json:"slug"`

	// Title Name of bundle (used in slug calculation)
	Title string `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message
	Error string `json:"error"`
}

// GetBundleResponse defines model for GetBundleResponse.
type GetBundleResponse struct {
	CreatedAt time.Time `json:"createdAt"`

	// Links Links in the bundle
	Links []Link `json:"links"`

	// Slug URL-safe identifier for the bundle
	Slug string `json:"slug"`

	// Title Name of bundle (used in slug calculation)
	Title string `json:"title"`
}

// Link defines model for Link.
type Link struct {
	// DisplayText Label for the url
	DisplayText *string `json:"displayText,omitempty"`

	// Note Short description for the link
	Note *string `json:"note,omitempty"`

	// Url URL in bundle
	Url string `json:"url"`
}

// CreateBundleJSONRequestBody defines body for CreateBundle for application/json ContentType.
type CreateBundleJSONRequestBody = CreateBundleRequest
