/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new bundle
         * @description Accepts a title and a list of links. Returns the created bundle title with a generated slug if none was provided.
         */
        post: operations["createBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a bundle by its slug
         * @description Returns the full bundle, including all of its links.
         */
        get: operations["getBundleBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateBundleRequest: {
            /** @description Name of bundle (used in slug calculation) */
            title: string;
            /** @description Links in the bundle */
            links: components["schemas"]["Link"][];
        };
        Link: {
            /**
             * Format: uri
             * @description URL in bundle
             */
            url: string;
            /** @description Label for the url */
            displayText?: string;
            /** @description Short description for the link */
            note?: string;
        };
        CreateBundleResponse: {
            /** @description Name of bundle (used in slug calculation) */
            title: string;
            /** @description URL-safe identifier for the bundle */
            slug: string;
            /** Format: date-time */
            createdAt: string;
        };
        GetBundleResponse: {
            /** @description URL-safe identifier for the bundle */
            slug: string;
            /** @description Name of bundle (used in slug calculation) */
            title: string;
            /** @description Links in the bundle */
            links: components["schemas"]["Link"][];
            /** Format: date-time */
            createdAt: string;
        };
        ErrorResponse: {
            /** @description Error message */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createBundle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBundleRequest"];
            };
        };
        responses: {
            /** @description Bundle created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateBundleResponse"];
                };
            };
            /** @description Validation error , missing required fields or malformed input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBundleBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique URL-safe identifier for the bundle */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bundle found successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetBundleResponse"];
                };
            };
            /** @description No bundle exists with the given slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
